dist: bionic

language: go

go:
  - 1.13.x

# Use most recent commits
git:
  depth: 1

# Don't skip the install step.
install: true

# Don't email me the results of the test runs.
notifications:
  email: true

# Download and extract the golangci-lint binary
before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.23.1
  - go get github.com/mattn/goveralls

script:
  # run a bunch of code checkers/linters in parallel
  - golangci-lint run
  # Run tests on coveralls.io
  - $GOPATH/bin/goveralls -service=travis-ci